export const CREATE_LOBBY_REQUEST = `CREATE_LOBBY_REQUEST`;
export const CREATE_LOBBY_SUCCESS = `CREATE_LOBBY_SUCCESS`;
export const CREATE_LOBBY_FAIL = `CREATE_LOBBY_FAIL`;

export const JOIN_LOBBY_REQUEST = `JOIN_LOBBY_REQUEST`;
export const JOIN_LOBBY_SUCCESS = `JOIN_LOBBY_SUCCESS`;
export const JOIN_LOBBY_FAIL = `JOIN_LOBBY_FAIL`;

export const FETCH_LOBBY_PLAYERS_REQUEST = `FETCH_LOBBY_PLAYERS_REQUEST`;
export const FETCH_LOBBY_PLAYERS_SUCCESS = `FETCH_LOBBY_PLAYERS_SUCCESS`;
export const FETCH_LOBBY_PLAYERS_FAIL = `FETCH_LOBBY_PLAYERS_FAIL`;
